################################################################################
# Copyright (c) 2018 Starburst Data, Inc. All rights reserved.
#
# All information herein is owned by Starburst Data Inc. and its licensors
# ("Starburst"), if any.  This software and the concepts it embodies are
# proprietary to Starburst, are protected by trade secret and copyright law,
# and may be covered by patents in the U.S. and abroad.  Distribution,
# reproduction, and relicensing are strictly forbidden without Starburst's prior
# written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED.  THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
# AND NONINFRINGEMENT ARE EXPRESSLY DISCLAIMED. IN NO EVENT SHALL STARBURST BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR ITS USE
# EVEN IF STARBURST HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Please refer to your agreement(s) with Starburst for further information.
################################################################################

version: '3.3'
services:

  metastore:
    build: .
    ports:
      - "9083:9083"
    restart: on-failure
    links:
      - "postgres:postgres.docker.starburstdata.com"
      - "mysql:mysql.docker.starburstdata.com"
    volumes:
      - /root/Fred_wu/docker-images-master/hive-metastore-unsecured/metastores /var/lib/hive/metastore
    environment:
      - HIVE_METASTORE_JDBC_URL
      - HIVE_METASTORE_DRIVER
      - HIVE_METASTORE_USER
      - HIVE_METASTORE_PASSWORD
      - S3_ENDPOINT
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
    healthcheck:
      test: "netstat -lpn | grep 9083"
      interval: 30s
      retries: 5

  # used only for debugging
  mysql:
    image: mysql:5.5.62
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hivemetastore
      MYSQL_DATABASE: hivemetastore
      MYSQL_USER: hivemetastore
      MYSQL_PASSWORD: hivemetastore
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: "mysql -u hivemetastore --password=hivemetastore -D hivemetastore -e 'select 1'"
      interval: 1s
      retries: 90

  postgres:
    image: postgres:9.6.10
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: hivemetastore
      POSTGRES_USER: hivemetastore
      POSTGRES_PASSWORD: hivemetastore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "psql -h localhost -U hivemetastore -c 'select 1' hivemetastore"
      interval: 1s
      retries: 90

  presto:
    image: starburstdata/presto:0.213-e.0.1
    healthcheck:
      test: "presto-cli-c 'select 1'"
      interval: 1s
      retries: 90
    links:
      - "postgres:postgres.docker.starburstdata.com"
      - "mysql:mysql.docker.starburstdata.com"
      - "metastore:metastore.docker.starburstdata.com"
    environment:
      - S3_ENDPOINT
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
    volumes:
      - ./files/etc/presto/catalog/hive.properties:/etc/presto/catalog/hive.properties
      - ./files/etc/presto/catalog/mysql.properties:/etc/presto/catalog/mysql.properties
      - ./files/etc/presto/catalog/postgresql.properties:/etc/presto/catalog/postgresql.properties
    command: /usr/lib/presto/bin/launcher run -Dhive.s3.aws-access-key="$S3_ACCESS_KEY" -Dhive.s3.aws-secret-key="$S3_SECRET_KEY" -Dhive.s3.endpoint="$S3_ENDPOINT"

volumes:
  postgres-data:
  mysql-data:
